# Generated by Django 4.1.7 on 2023-03-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(max_length=3)),
                ('sepal_ratio', models.FloatField(max_length=3)),
                ('sepal_width', models.FloatField(max_length=3)),
                ('petal_length', models.FloatField(max_length=3)),
                ('petal_ratio', models.FloatField(max_length=3)),
                ('petal_width', models.FloatField(max_length=3)),
                ('species', models.CharField(max_length=100)),
            ],
        ),
    ]
